mcps:
  msa_mcp:
    dependencies: []
    description: Access to AlphaFold Protein Structure Database
    env_vars: {}
    runtime: node
    server_args:
    - $MCP_PATH/build/index.js
    server_command: node
    setup_commands:
    - npm install
    - npm run build
    source: Augmented Nature
    url: https://github.com/Augmented-Nature/AlphaFold-MCP-Server
