mcps:
  msa_mcp:
    dependencies: []
    description: Generate Multiple Sequence Alignments (MSA) using ColabFold/MMseqs2
      server
    env_vars: {}
    path: /home/xux/Desktop/ProteinMCP/ProteinMCP/tool-mcps/msa_mcp
    runtime: python
    server_args:
    - src/msa_mcp.py
    server_command: python
    setup_commands:
    - pip install fastmcp requests
    source: Tool
    url: https://github.com/Biomolecular-Design-Nexus/msa_mcp
