mcps:
  interpro:
    dependencies: []
    description: Protein domain and family analysis, functional annotation, and GO
      term mapping
    env_vars: {}
    path: /home/xux/Desktop/ProteinMCP/ProteinMCP/tool-mcps/public/bio-mcp-interpro
    runtime: python
    server_args:
    - -m
    - src.server_with_queue
    server_command: python
    setup_commands:
    - pip install -e .
    source: bio-mcp
    url: https://github.com/bio-mcp/bio-mcp-interpro
  msa_mcp:
    dependencies: []
    description: Access to AlphaFold Protein Structure Database
    env_vars: {}
    runtime: node
    server_args:
    - $MCP_PATH/build/index.js
    server_command: node
    setup_commands:
    - npm install
    - npm run build
    source: Augmented Nature
    url: https://github.com/Augmented-Nature/AlphaFold-MCP-Server
